# Generated by Django 5.1.7 on 2025-04-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_restaurant"),
    ]

    operations = [
        migrations.CreateModel(
            name="CleanRestaurant",
            fields=[
                (
                    "business_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                ("postal_code", models.CharField(max_length=20)),
                ("categories", models.TextField()),
                ("stars_x", models.FloatField()),
                ("review_count", models.IntegerField()),
                ("phone", models.CharField(max_length=20)),
                ("attributes", models.TextField(null=True)),
                ("hours", models.TextField(null=True)),
                ("website", models.TextField(null=True)),
            ],
            options={
                "db_table": "clean_restaurants",
                "managed": False,
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="business",
        ),
        migrations.DeleteModel(
            name="Restaurant",
        ),
        migrations.DeleteModel(
            name="Business",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
